@extends('layouts.main')
@section('others-js')
    {{--<script src="{{ asset('js/access.js') }}"></script>--}}
@endsection
@section('pageTitle')
    | Terms of Service
@endsection
<style>

</style>
@section('content')
    <div class="col-md-8 col-md-offset-2">
        <h1 class="h1-simplepage pull-left">Terms of Service</h1>
        <div class="simplepage-content" id="faq-content">
            <h2>PostHurry Terms of Service</h2>

            <p>
                Welcome to PostHurry. These terms and conditions (“Terms of Service” or “Agreement”) govern your access to and use of the products and services offered by PostHurry, (“PostHurry”) accessible via the website, www.getposthurry.com or posthurry.com, including successor domain names or sites as well, and any and all information, text, graphics, photos, or other materials uploaded, downloaded, or appearing on the Services (as defined below).
            </p>
            <p>
                BY ACCESSING AND USING THE SERVICES IN ANY MANNER, YOU ARE "ACCEPTING" AND AGREEING TO BE BOUND BY THESE TERMS OF SERVICE TO THE EXCLUSION OF ALL OTHER TERMS. IF YOU DO NOT UNCONDITIONALLY ACCEPT THESE TERMS IN THEIR ENTIRETY, YOU SHALL NOT (AND SHALL HAVE NO RIGHT TO) ACCESS OR USE THE SERVICES. IF THE TERMS OF THIS AGREEMENT ARE CONSIDERED AN OFFER, ACCEPTANCE IS EXPRESSLY LIMITED TO SUCH TERMS. THESE TERMS SHOULD BE READ IN CONJUNCTION WITH
                <a href="/privacy">POSTHURRY’S PRIVACY POLICY</a>.
            </p>
            <p>
                Wherever used in these Terms of Service, “you”, “your”, “Customer”, or similar terms means the person or legal entity accessing or using the Services.  If you are accessing and using the Services on behalf of a company (such as your employer) or other legal entity, you represent and warrant that you have the authority to bind that company or other legal entity to these Terms of Service.
            </p>
            <p>
                PostHurry reserves the right, at any time, to update and change any or all of these Terms of Service, in its sole discretion, including but not limited to the fees and charges associated with the use of the Services. If PostHurry does so, it will post the modified Terms of Service on the Site, though we will notify you of any changes that, in our sole discretion, materially impact these Terms of Service.  Continued use of the Services after any such changes have been made shall constitute your consent to such changes. You are responsible for regularly reviewing the most current version of the Terms of Service. When PostHurry changes these Terms of Service, PostHurry will modify the "Last Modified" date above.
            </p>

            <h3>1. Definitions</h3>
            <p>
                “Authorization Form” means a document issued by PostHurry and executed or otherwise agreed upon by authorized representatives of the Parties which specifies, among other things, a description of the Services, the Fees (as defined below), the number of Seats purchased, the Term (as defined below), and any other details specifically related to the Services.
            </p>
            <p>
                “Authorized Users” means individuals who are directly accessing the Services via an online sign-up process, or individual users authorized by you to use the Services and who you have supplied user identifications and passwords to. Authorized Users may include your employees, consultants, contractors, agents, or your other designees, but shall not include any employee or agent of any PostHurry competitor.
            </p>
            <p>“Customer Content” means all information and data (including text, images, photos, videos, audio, and documents) or any other content in any media and format provided or made available to PostHurry by or on your behalf in relation to the use of the Services.</p>
            <p>“Fair Use Policy” means the limits placed on usage as described in <a href="#2_6">Section 2.6</a>.</p>
            <p>“Mentions” means the information, including links, posts, and excerpts, that has been made publicly available and obtained by PostHurry on your behalf from the Internet, and data derived therefrom, including reports, summaries, graphs, and charts.</p>
            <p>“Query” means a search string that an Authorized User uses to define what words and phrases must be present in a Mention for that Mention to be included in the applicable stream.</p>
            <p>“Seat” means a single subscription associated with a single log-in to the Site, assigned to one Authorized User.</p>
            <p>“Services” means PostHurry Free and other PostHurry products and services made available via PostHurry’s proprietary software delivered through the Site and mobile applications that provide for a single log-in, centralized dashboard that enables you and Authorized Users to manage and publish social media content to multiple Supported Platforms, including any modifications or Updates (as defined below).</p>
            <p>“Supported Platform(s)” means the social networking site(s) currently supported by the Services, including Facebook as described via the Site.</p>
            <p>“Taxes” means all taxes, assessments, charges, fees, and levies that may be levied or based upon the sale or license of goods and/or services, as the case may be, including all sales, use, goods and services, value added, and excise taxes, custom duties, and assessments together with any installments with respect thereto, and any interest, fines, and penalties with respect thereto, imposed by any governmental authority (including federal, state, provincial, municipal, and foreign governmental authorities).</p>


            <h3>2. PostHurry Services</h3>
            <p><b>2.1 Services and Support.</b></p>
            <p>
                If you select PostHurry Free: During the Term (as defined below), subject to the terms and conditions of this Agreement, and solely for your personal or own business purposes, PostHurry shall use commercially reasonable efforts to make the PostHurry Free services available to you.
            </p>
            <p>If you select PostHurry Pro: During the Term (as defined below), subject to the terms and conditions of this Agreement, and solely for your personal or internal business purposes, PostHurry shall use commercially reasonable efforts to make the PostHurry Pro services available to you and your Authorized Users for the number of Seats purchased.  PostHurry will provide PostHurry Plan customers with standard support 24 hours per day from Monday to Friday, and between the hours of 9am and 5pm Eastern Time on Saturday, Sunday, and on statutory holidays in Canada. You may submit a maximum of 4 support tickets per day. Expected response times after a ticket has been submitted by a PostHurry Plan user during the support hours through info@getposthurry.com shall be 48 hours from the time the ticket is logged.</p>
            <p>If you select other PostHurry Free or PostHurry Plan products and services: During the applicable term, subject to the terms and conditions of this Agreement (including any terms that only apply to your access to and use of certain PostHurry services), and solely for your personal or internal business purposes, PostHurry shall use commercially reasonable efforts to make such PostHurry services available to you and your Authorized Users, if applicable, for the quantities purchased.</p>

            <p>2.2 Updates and Functionalities. You acknowledge that from time to time PostHurry may apply updates to the Services and that such updates may result in changes in the appearance and/or functionality of the Services (including the addition, modification, or removal of functionality, features, or content). Excluding the addition of wholly new products, PostHurry shall provide, implement, configure, install, support, and maintain at its own cost any and all updates, upgrades, enhancements, improvements, releases, corrections, bug fixes, patches, and modifications to the Services (collectively, the “Updates”). You acknowledge that the Services interoperate with several Supported Platforms, and that the Services provided are highly dependent on the availability of such Supported Platforms. If at any time any Supported Platforms cease to make their programs available to PostHurry on reasonable terms, PostHurry may cease to provide such features to you without entitling you to refund, credit, or other compensation.</p>
            <p>2.3 Acceptable Use. You shall (i) be responsible for your and your Authorized Users’ compliance with these Terms of Service, including the Fair Use Policy; (ii) be solely responsible for the accuracy, quality, integrity, and legality of Customer Content and of the means by which you acquired or generated Customer Content; (iii) use commercially reasonable efforts to prevent unauthorized access to or use of the Services, including keeping you password and user name confidential and not permitting any third party to access or use your user name, password, or account for the Services; (iv) be solely responsible and liable for all activity conducted through your account in connection with the Services; (v) promptly notify PostHurry if you become aware of or reasonably suspects any security breach, including any loss, theft, or unauthorized disclosure or use of your (or any Authorized User’s) user name, password, or account; (vi) use the Services only in accordance with applicable laws and government regulations; (vii) comply in all respects with all applicable terms of the Third-Party Services that you subscribe to or otherwise access in connection with your use of the Services. You must not (a) make the Services available to anyone other than to your Authorized Users; (b) allow more than one individual Authorized User to use a Seat; (c) sell, trade, or otherwise transfer your Seats to another party; (d) use the Services to store or transmit any content, including Customer Content, that may be infringing, defamatory, threatening, harmful, or otherwise tortious or unlawful, including any content that may violate intellectual property, privacy, rights of publicity, or other laws, or send spam or other unsolicited messages in violation of applicable law; (e) upload to, or transmit from, the Services any data, file, software, or link that contains or redirects to a virus, Trojan horse, worm, or other harmful component; (f) attempt to reverse engineer, de-compile, hack, disable, interfere with, disassemble, copy, or disrupt the integrity or the performance of the Services, any third-party use of the Services, or any third-party data contained therein (except to the extent such restrictions are prohibited by applicable law); (g) access the Services in order to build a competitive product or service or copy any ideas, features, functions, or graphics of the Services; (h) attempt to gain unauthorized access to the Services or its related systems or networks; or (i) authorize, permit, or encourage any third party to do any of the above.</p>
            <p>2.4 Mentions. You understand that by using the Services you may be exposed to third-party content, information, and Mentions that might be unlawful, offensive, harmful, inaccurate or otherwise inappropriate. PostHurry does not own, control, or review Mentions, and unless Customer creates the content of Mentions, Mentions shall not be considered “Customer Content” under any circumstances. Mentions may be indecent, offensive, inaccurate, unlawful, or otherwise objectionable. PostHurry has no obligation to preview, verify, flag, modify, filter, or remove any Mentions, even if requested to do so, although PostHurry may do so in its sole discretion. Your use of Mentions is at your sole risk, and PostHurry shall not be liable to you or any third party in relation to Mentions.</p>
            <p>2.5 Fair Use Policy. PostHurry may suspend your access to the Services for abusive practices that degrade the performance of the Services for you and/or other customers of PostHurry.</p>
            <p id="2_6">2.6 Third-Party Products and Services. You acknowledge that the Services may enable or assist you to access, interact with, and/or purchase services from Supported Platforms and other third parties via third-party websites or applications (collectively, the “Third-Party Services”). When you access the Third-Party Services, you will do so at your own risk. Any use of Third-Party Services is governed solely by the terms and conditions of such Third-Party Services (and you shall comply with all such terms and conditions), and any contract entered into, or any transaction completed via any Third-Party Services, is between you and the relevant third party, and not PostHurry. PostHurry makes no representation and shall have no liability or obligation whatsoever in relation to the content or use of, or correspondence with, any such Third-Party Services or any transactions completed and any contract entered into by you with any such third party.</p>
            <p>2.7 Non-Exclusivity. You acknowledge that the rights granted to you under this Agreement are non-exclusive and that nothing in this Agreement will be interpreted or construed to prohibit or in any way restrict PostHurry’s right to license, sell, or otherwise make available the Services to any third party or perform any services for any third party.</p>

            <h3>3. Intellectual Property</h3>
            <p>3.1 PostHurry Services. As between you and PostHurry, PostHurry retains all right, title, and interest in and to the Services. Nothing herein shall be construed to restrict, impair, encumber, alter, deprive, or adversely affect the Services or any of PostHurry’s rights or interests therein or any other PostHurry intellectual property, brands, information, content, processes, methodologies, products, goods, services, materials, or rights, tangible or intangible. All rights, title, and interest in and to the Services not expressly granted in this Agreement are reserved by PostHurry. You may from time to time provide suggestions, comments or other feedback to PostHurry with respect to the Services (“Feedback”). Feedback, even if designated as confidential by you, shall not create any confidentiality obligation for PostHurry notwithstanding anything else. You shall, and hereby do, grant to PostHurry a non-exclusive, worldwide, perpetual, irrevocable, transferable, sublicensable, royalty-free, fully paid-up license to use and exploit the Feedback for any purpose.</p>
            <p>3.2 Customer Content. You grant PostHurry a limited, worldwide, non-exclusive, non-transferable (except as set forth in Section 9.1) license, without a right of sublicense, to access, use, reproduce, electronically distribute, transmit, perform, format, display, store, archive, and index the Customer Content for the purpose of supporting your use of the Services and providing Services to you. PostHurry may also use Customer Content for the purpose of supporting and developing the Site, provided that when doing so, PostHurry shall only use Customer Content in an anonymized and aggregated way. Subject only to the limited license expressly granted herein, you and your Authorized Users shall retain all right, title and interest in and to the Customer Content and all intellectual property rights therein. Nothing in this Agreement will confer on PostHurry any right of ownership or interest in the Customer Content or the intellectual property rights there</p>
            <p>3.3 Responsibility for Customer Content and Mentions. You are solely responsible for the Customer Content that you or Authorized Users upload, publish, display, link to, or otherwise make available via the Services, and you agree that PostHurry is only acting as a passive conduit for the online distribution and publication of the Customer Content and the online display of Queries and Mentions. PostHurry will not review, share, distribute, or reference any Customer Content or Mentions except as provided herein, as provided in <a
                        href="/privacy">PostHurry’s privacy policy</a> and <a href="javascript:void(0);">copyright policy</a>, or as may be required by law. Notwithstanding the foregoing, PostHurry retains the authority to remove any Customer Content uploaded that it deems in violation of this Agreement, at its sole discretion.</p>

            <h3>4. PostHurry Products and Fees</h3>
            <p>4.1 Purchases By Authorization Form. If an Authorization Form is issued for the purchase of Services, you agree to pay all fees as and when described per the Authorization Form(s). PostHurry shall invoice you for the Fees in the currency set forth on the applicable Authorization Form. Unless otherwise stated on the Authorization Form, all invoices shall be payable within 30 days of the invoice date. Any disputed amounts shall not affect payment of non-disputed amounts. You shall make payments to the entity and address set forth in the invoice.</p>
            <p>4.2 PostHurry Plan and Other Paid Services.  For PostHurry Plan and other paid services made available through PostHurry Free and PostHurry Plan (“Paid Services”), you must provide PostHurry with a valid credit card or other forms of cash payment (e.g., PayPal account) to pay for such services. If you are purchasing PostHurry Plan or Paid Services via an online purchase, you can choose to purchase on a monthly or yearly subscription. In addition, you agree that PostHurry has permission to retain and/or share with financial institutions and payment processing firms (including any institutions or firms PostHurry retains in the future) your submitted payment information in order to process your purchase. Depending on where you transact with us, the type of payment method used and where your payment method was issued, your transaction with us may be subject to foreign exchange fees or differences in prices, including because of exchange rates. PostHurry does not support all payment methods, currencies, or locations for payment. If the payment method you use with us, such as a credit card, reaches its expiration date and you do not edit your payment method information or cancel or downgrade your account to a PostHurry Free account, you authorize PostHurry to continue billing your credit card and/or PayPal account and you remain responsible for any uncollected amounts. All applicable taxes are calculated based on the billing information you provide us at the time of purchase.</p>
            <p>4.3 Free Trial Period. If you sign up online for a PostHurry Plan account with a free initial trial period (the “Free Trial”), you must provide PostHurry with a valid credit card or PayPal account. If you do not cancel your account or downgrade your PostHurry Plan account within the first 7 days after it was initially created, your credit card or PayPal account will automatically be billed starting on the first day after the Free Trial is over. If you cancel or downgrade your PostHurry Pro account prior to the beginning of the 8th day, no charges will be put through your credit card or PayPal account. Please note that other Paid Services (such as apps purchased via the PostHurry app directory) will require to be uninstalled separately via the app directory to avoid charges being incurred on the 31st day. The Free Trial is only available to first time users of PostHurry Plan.</p>
            <p>4.4 Subscription Services; Auto-renewal and Cancellation.  If you are purchasing PostHurry Plan or Paid Services on a subscription basis, you can choose to purchase on a monthly or yearly subscription and your subscription will renew automatically. Subscriptions are billed in advance on a monthly or yearly basis (as per the option chosen when you purchased such services) and are non-refundable for the subscription period they are purchased for. You agree that PostHurry may process your credit card or PayPal account on each monthly, annual, or other renewal term (based on the applicable billing cycle), on the calendar day corresponding to the first day you subscribed to a paid subscription. If your paid subscription to PostHurry Plan or other Paid Services began on a day not contained in a subsequent month (e.g., your service began on January 30 and there is no February 30), PostHurry will process your payment on the last day of such month. You may elect to cancel or downgrade your PostHurry Plan account at any time. If you purchased Paid Services in association with a monthly plan, PostHurry will issue PostHurry credits equivalent to the prorated prepaid fees of such Paid Services on the date of the cancellation. Such credits are non-refundable, but can be used against the purchase of any future PostHurry services. If you subscribed to a yearly plan, any cancellation will only be effective at the end of the then-current annual billing period and no credits or refunds will be issued to you for prepaid fees.</p>
            <p>4.5 Late Payment. If any amounts due hereunder are not received by PostHurry by the due date, then at PostHurry’s discretion, such charges may accrue late interest at the rate of 12% per year or the maximum rate permitted by law, whichever is lower, from the date such payment was due until the date paid. In addition, upon 10 days' written notice, PostHurry may suspend your access to the Services if PostHurry does not receive the amounts invoiced hereunder at the expiration of such period.</p>
            <p>4.6 Taxes and Withholdings. You are responsible for paying all Taxes associated with your purchase of services. If PostHurry has the legal obligation to pay or collect Taxes for which you are responsible under this Section, the appropriate amount shall be invoiced to and paid by you, unless you provide PostHurry with a valid tax exemption certificate authorized by the appropriate taxing authority. Any and all payments by or on account of the compensation payable under this Agreement shall be made free and clear of and without deduction or withholding for any Taxes. If you are required to deduct or withhold any Taxes from such payments, then the sum payable shall be increased as necessary so that, after making all required deductions or withholdings, PostHurry receives an amount equal to the sum it would have received had no such deduction or withholding been made.</p>

            <h3>5. Term and Termination</h3>
            <p>5.1 PostHurry Free and Plan Services. If you sign-up for a PostHurry Free or PostHurry Plan account, this Agreement shall commence on the day you access the Services for the first time and shall continue until your account is cancelled and you cease using our Services (the “Term”).</p>
            <p>5.2 Termination. If you violate the letter or spirit of these Terms of Service, abuse the Services, or otherwise create risk or possible legal exposure to PostHurry, PostHurry can terminate or suspend your PostHurry Account at our sole discretion. PostHurry will notify you by email or at the next time you attempt to access your account. You may also cancel or disable your PostHurry Free account at any time.</p>
            <p>5.4 Survival. Any provision of this Agreement which, either by its terms or to give effect to its meaning, must survive, and such other provisions which expressly, or by their nature, are intended to survive termination shall survive the expiration or termination of this Agreement.</p>

            <h3>6. Warranty Disclaimer</h3>
            <p>7. Indemnification</p>
            <p>7.1 Your Indemnification. You shall defend, indemnify, and hold harmless PostHurry, its affiliates, directors, officers, employees, and agents from and against all claims, losses, damages, penalties, liability, and costs, including reasonable attorneys’ fees, of any kind or nature which are in connection with or arising out of a claim (a) alleging that the Customer Content or your use of the Services infringes or violates the intellectual property rights, privacy rights, or other rights of a third party or violates applicable law; (b) relating to, or arising from, Customer Content, or your breach of Section 2.3 or Section 2.6; or (c) relating to, or arising from, Third-Party Services.</p>

            <h3>8. Limitation of Liability</h3>
            <p>SOME COUNTRIES DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY IN CONTRACTS WITH CONSUMERS AND AS A RESULT THE CONTENTS OF THIS SECTION MAY NOT APPLY TO YOU.  TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL POSTHURRY’S AGGREGATE LIABILITY FOR ALL CLAIMS OF ANY KIND, INCLUDING ANY CLAIMS ARISING OUT OF OR RELATED TO THIS AGREEMENT, WHETHER BY STATUTE, CONTRACT, TORT, OR UNDER ANY OTHER THEORY OF LIABILITY, EXCEED THE GREATER OF (A) THE fees paid by YOU FOR THE SERVICES HEREUNDER DURING THE three (3) month PERIOD IMMEDIATELY PRECEDING THE DATE ON WHICH THE CAUSE OF ACTION AROSE AND (B) US$500. POSTHURRY DOES NOT OFFER ANY WARRANTY OR REMEDIES FOR THE INTERRUPTION OR CESSATION OF ACCESS OR TRANSMISSION TO OR FROM THE SERVICES.</p>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL POSTHURRY, ITS DIRECTORS, EMPLOYEES, AGENTS, OR LICENSORS BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, INCLUDING DAMAGES FOR LOSS OF PROFITS, GOODWILL USE, OR DATA OR OTHER INTANGIBLE LOSSES, THAT RESULT FROM THE USE OF, OR INABILITY TO USE, THE SERVICES OR ANY OTHER ASPECT OF THIS AGREEMENT. UNDER NO CIRCUMSTANCES WILL POSTHURRY BE RESPONSIBLE FOR ANY DAMAGE, LOSS, OR INJURY RESULTING FROM HACKING, TAMPERING, OR OTHER UNAUTHORIZED ACCESS OR USE OF THE SERVICES OR YOUR ACCOUNT OR THE INFORMATION CONTAINED THEREIN.</p>
            <p>THE PARTIES ACKNOWLEDGE AND AGREE THAT THE ESSENTIAL PURPOSE OF THIS SECTION IS TO ALLOCATE THE RISKS UNDER THESE TERMS BETWEEN THE PARTIES AND LIMIT THEIR POTENTIAL LIABILITY GIVEN THE FEES CHARGED UNDER THIS AGREEMENT, WHICH WOULD HAVE BEEN SUBSTANTIALLY HIGHER IF PostHurry WERE TO ASSUME ANY FURTHER LIABILITY OTHER THAN AS SET FORTH HEREIN. THE PARTIES HAVE RELIED ON THESE LIMITATIONS IN DETERMINING WHETHER TO ENTER INTO THESE TERMS. NOTHING IN THIS AGREEMENT IS INTENDED TO EXCLUDE OR RESTRICT OR SHALL BE CONSTRUED AS EXCLUDING OR RESTRICTING THE LIABILITY OF POSTHURRY FOR (I) DEATH OR PERSONAL INJURY CAUSED BY THE NEGLIGENCE OF POSTHURRY, ITS EMPLOYEES, OR ITS AGENTS; (II) WILLFUL MISCONDUCT OF POSTHURRY; OR (III) ANY LIABILITY WHICH CANNOT BE LIMITED OR EXCLUDED BY APPLICABLE LAW.</p>

            <h3>9. General</h3>
            <p>9.1 Assignment. You may not assign or otherwise transfer any of your rights or obligations hereunder, whether by merger, sale of assets, change of control, operation of law or otherwise, without the prior written consent of PostHurry (not to be unreasonably withheld), and any attempted assignment or transfer without such consent will be void. PostHurry may freely assign or delegate all rights and obligations under this Agreement, fully or partially without notice to you. PostHurry may also substitute, by way of unilateral novation, effective upon notice to you, PostHurry Media Inc. for any third party that assumes our rights and obligations under this Agreement.</p>
            <p>9.2 Amendment. PostHurry reserves the right to modify, supplement, or replace the terms of this Agreement, effective upon posting on the PostHurry website or notifying you otherwise. Your continued use of the Services after the effectiveness of that update will be deemed to represent your agreement with, and consent to be bound by, the new terms. Except for changes made by PostHurry as described here, no other amendment or modification of this Agreement shall be effective unless set forth in a written agreement bearing a written signature by PostHurry and you.</p>
            <p>9.3 Severability. Each provision of this Agreement is severable. If any provision of this Agreement is or becomes illegal, invalid, or unenforceable in any jurisdiction, the illegality, invalidity, or unenforceability of that provision will not affect the legality, validity, or enforceability of the remaining provisions of this Agreement or of that provision in any other jurisdiction.</p>
            <p>9.4 Notices. For purposes of service messages and notices about the Services, PostHurry may place a banner notice across its pages to alert you to certain changes such as modifications to this Agreement. Alternatively, notice may consist of an email from PostHurry to an email address associated with your account, even if PostHurry has other contact information. You also agree that PostHurry may communicate with you through your PostHurry account or through other means including email, mobile number, telephone, or delivery services including the postal service about your PostHurry account or services associated with PostHurry. You acknowledge and agree that PostHurry shall have no liability associated with or arising from your failure to do so maintain accurate contact or other information, including, but not limited to, your failure to receive critical information about the Services. <p>9.5 Waivers. No waiver of any provision of this Agreement is binding unless it is in writing and signed by all parties to this Agreement, except that any provision which does not give rights or benefits to particular parties may be waived in writing, signed only by those parties who have rights under, or hold the benefit of, the provision being waived if those parties promptly send a copy of the executed waiver to all other parties. No failure to exercise, and no delay in exercising, any right or remedy under this Agreement will be deemed to be a waiver of that right or remedy. No waiver of any breach of any provision of this Agreement will be deemed to be a waiver of any subsequent breach of that provision or of any similar provision.</p>
            <p>9.6 Nature of Relationship. No agency, partnership, joint venture, or employment relationship is created as a result of this Agreement and neither party has any authority of any kind to bind the other in any respect.</p>
            <p>9.7 Force Majeure. Except for payment obligations, neither party shall be liable for any failure to perform its obligations hereunder where such failure results from any cause beyond such party’s reasonable control, including the elements; fire; flood; severe weather; earthquake; vandalism; accidents; sabotage; power failure; denial of service attacks or similar attacks; Internet failure; acts of God and the public enemy; acts of war; acts of terrorism; riots; civil or public disturbances; strikes, lock-outs, or labor disruptions; and any laws, orders, rules, regulations, acts, or restraints of any government or governmental body or authority, civil or military, including the orders and judgments of courts.</p>
            <p>9.8 Governing Law. This Agreement and your relationship with PostHurry shall be governed exclusively by, and will be enforced, construed, and interpreted exclusively in accordance with, the laws applicable in Nashville, Tennessee, United States of America, and shall be considered to have been made and accepted in Nashville, Tennessee, United States of America, without regard to its conflict of law provisions. All disputes under this Agreement will be resolved by the courts of Nashville, Tennessee in the United States of America. In any action or proceeding to enforce rights under this Agreement, the prevailing party shall be entitled to recover costs and attorneys’ fees.</p>
            <p>9.9 Entire Agreement. The terms of this Agreement, together with any applicable Authorization Form, all exhibits, and PostHurry’s Privacy Policy, constitute the entire agreement between the parties with respect to the use of the Services and supersede any prior or inconsistent agreements, negotiations, representations, and promises, written or oral, with respect to the subject matter and is binding upon the parties and their permitted successors and assigns. In the event of any conflict between this Agreement and the terms of an Authorization Form, the provisions of the Authorization Form shall prevail. The terms of this Agreement will apply to all orders you submit to PostHurry for PostHurry Free and PostHurry Plan accounts and shall supersede any additional terms, which may be incorporated in a purchase order form, or any other form you generate. Any such terms shall be null and void.</p>


        </div>
    </div>
@endsection
